[[rules]]
id = "jwt"
description = "JSON Web Token"
regex = "(?i)\\b(ey[0-9a-z]{30,34}\\.ey[0-9a-z-\\/_]{30,500}\\.[0-9a-zA-Z-\\/_]{10,200}={0,2})(?:['|\\\"|\\n|\\r|\\s|\\x60|;]|$)"
keywords = [
    "ey",
]